name: retrace2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow=24.10.5
  - fastqc=0.12.1
  - multiqc=1.28
  - python=3.9
  - trim-galore=0.6.10
  - methylpy=1.4.7
  # - bwa
  # - samtools
  # - bedtools
  # - pandas
  # - numpy
  # - matplotlib
  # - seaborn
